### ISSUE TITLE
Unable to create user id 

### ISSUE THREAD

**Issue by suren-7** [socioboard/Socioboard-5.0#169]
Installed socioboard 4.0 as per document but now unable to create user id. not getting any error.

**Comment by sureshbabu1995** [comment]
Hi, @suren-7 

If you can give some elaborated description where the issue you facing I can help you with that. 

So, please mention some description of the error , that what you trying and where you getting an error, because you can create the user by 2 ways directly from node side or using Web-interface ( PHP )

**Comment by fairhopeweb** [comment]
@suren-7 I'm having the same issue on the PHP install. It will not accept my new user, social logins don't work. I can't tell from documentation if there is a basic root or pre-installed user?

**Comment by AishwaryaMurali** [comment]
Hi, have you updated the .env file of php with all the node services link ? 
And, is all nodejs setup done?

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
