### ISSUE TITLE
Create User error

### ISSUE THREAD

**Issue by Ponomikola** [socioboard/Socioboard-5.0#172]
I have set up the Socioboard according to the documentation provided on my local windows system. But in order to use it, I tried to create user using email ID from front end and it gave me error like
"Validation error: profile_picture is not in valid url.".

Also if I try to create user with FB or Google it gave error as:

Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

What could be the error and how can i create user to use it.
![socio](https://user-images.githubusercontent.com/66824892/84488214-b610b500-ac54-11ea-83c5-7b81517d7c2f.PNG)

**Comment by Xlomi** [comment]
The problem is with "api\library\node_modules\validator\lib\isURL.js" look for the line "if (!(0, _isIP.default)(host) && !(0, _isFQDN.default)(host, options) && (!ipv6 || !(0, _isIP.default)(ipv6, 6))) {" (line 134 me)
when debugging the code, I noticed that all of these are "true" so the return value is false.
I haven't dug too deep into this - for the time being I commented out the "if '' statement. I believe this has something to do with running the PHP app on a specific port, but I'm not sure.

**Comment by Csurlee** [comment]
Hello, something new?
I have the same problem ...

Thanks

**Comment by BloodyIron** [comment]
Actually commenting the line out didn't work for me, so I set the result from "false" to "true".

For me, because I'm doing this as a demo, I think it's failing because I'm not using a FQDN, and/or HTTPS.

The experience with this tool is very horrible and the quality of programming here is amateur AT BEST. Here's hoping the tool is worth the pain it takes to get going.

**Comment by kchizi** [comment]
Have you set up the correct  "APP_URL=" in socioboard-web-php ?

Ensure the correct APP_URL= is set in the laravel environment file

**Comment by socioboard** [comment]
Hi we've done **a Major Update**, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
